### DISCUSSION TITLE
How can I handle out of memory in CUDA?

### DISCUSSION THREAD

**Discussion by erotavlas** [explosion/spaCy#7720] [Help: Coding & Implementations] [answered]
I keep getting an out of memory on my GPU (gtx 1060 with 6GB), as the training started, the memory usage just keeps gradually increasing and then it produces an error.  Do you have any suggestions?  I tried reducing the batch size to 32 and then also 16 (from 128) but that didn't help.  Do you know if there are any other settings I can change?

This was the batch size parameter that I changed
```
[nlp]
lang = "en"
pipeline = ["transformer","ner"]
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
batch_size = 16
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}
```

```
(spacy3.0) PS D:\training\spacy> python -m spacy train config.cfg --output output --gpu-id 0
ℹ Using GPU: 0

=========================== Initializing pipeline ===========================
[2021-04-09 08:41:56,958] [INFO] Set up nlp object from config
[2021-04-09 08:41:56,966] [INFO] Pipeline: ['transformer', 'ner']
[2021-04-09 08:41:56,969] [INFO] Created vocabulary
[2021-04-09 08:41:58,923] [INFO] Added vectors: spacy_word2vec_2.0.0.0
[2021-04-09 08:41:58,924] [INFO] Finished initializing nlp object
[2021-04-09 08:42:35,207] [INFO] Initialized pipeline components: ['transformer', 'ner']
✔ Initialized pipeline

============================= Training pipeline =============================
ℹ Pipeline: ['transformer', 'ner']
ℹ Initial learn rate: 0.0
E    #       LOSS TRANS...  LOSS NER  ENTS_F  ENTS_P  ENTS_R  SCORE
---  ------  -------------  --------  ------  ------  ------  ------
⚠ Aborting and saving the final best model. Encountered exception:
RuntimeError('CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 6.00 GiB
total capacity; 4.14 GiB already allocated; 38.50 MiB free; 4.57 GiB reserved in
total by PyTorch)')
Traceback (most recent call last):
  File "D:\Anaconda\envs\spacy3.0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda\envs\spacy3.0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\cli\_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\cli\train.py", line 59, in train_cli
    train(nlp, output_path, use_gpu=use_gpu, stdout=sys.stdout, stderr=sys.stderr)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\training\loop.py", line 114, in train
    raise e
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\training\loop.py", line 98, in train
    for batch, info, is_best_checkpoint in training_step_iterator:
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\training\loop.py", line 212, in train_while_improving
    score, other_scores = evaluate()
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\training\loop.py", line 267, in evaluate
    scores = nlp.evaluate(dev_corpus(nlp))
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\language.py", line 1350, in evaluate
    for doc, eg in zip(
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy\util.py", line 1479, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy_transformers\pipeline_component.py", line 202, in pipe
    self.set_annotations(subbatch, self.predict(subbatch))
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy_transformers\pipeline_component.py", line 218, in predict
    activations = self.model.predict(docs)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\thinc\model.py", line 312, in predict
    return self._func(self, X, is_train=False)[0]
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\spacy_transformers\layers\transformer_model.py", line 142, in forward
    tensors, bp_tensors = transformer(wordpieces, is_train)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\thinc\model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\thinc\layers\pytorchwrapper.py", line 80, in forward
    Ytorch, torch_backprop = model.shims[0](Xtorch, is_train)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\thinc\shims\pytorch.py", line 29, in __call__
    return self.predict(inputs), lambda a: ...
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\thinc\shims\pytorch.py", line 38, in predict
    outputs = self._model(*inputs.args, **inputs.kwargs)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 798, in forward
    encoder_outputs = self.encoder(
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 498, in forward
    layer_outputs = layer_module(
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 433, in forward
    layer_output = apply_chunking_to_forward(
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\transformers\modeling_utils.py", line 1787, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 445, in feed_forward_chunk
    intermediate_output = self.intermediate(attention_output)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 347, in forward
    hidden_states = self.intermediate_act_fn(hidden_states)
  File "D:\Anaconda\envs\spacy3.0\lib\site-packages\torch\nn\functional.py", line 1459, in gelu
    return torch._C._nn.gelu(input)
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 6.00 GiB total capacity; 4.14 GiB already allocated; 38.50 MiB free; 4.57 GiB reserved in total by PyTorch)

```

![image](https://user-images.githubusercontent.com/10454265/114181792-f17d1e00-990f-11eb-9fe5-f30c6e3fb8e2.png)

**Comment by tristancatteeuw** [comment]
Not sure but it might simply be that 6GB of VRAM is not enough. If you check the spacy documentation, 10GB minimum is recommended.
Otherwise maybe try a lighter model like Distilbert and see if it works?

**Comment by erotavlas** [comment, marked as answer]
I was able to get it to work by reducing the batch training size to about 8 and also the max_batch_items to something like 1024 or 512. under the [components.transformer] section.  The values were dependent on the transformer model I used.
