### ISSUE TITLE
GPU and multiprocessing leads to ' initialization error'

### ISSUE THREAD

**Issue by zhanwen** [explosion/spaCy#5507]
```
spacy.prefer_gpu()
nlp = spacy.load('en_core_web_sm', disable=["tagger", "parser"]) 
docs = nlp.pipe(texts, batch_size=128, n_process=2, disable=["tagger", "parser"])
```
NOTE :
if I am using n_process=1 the code runs fine.
If I am not using the gpu the code also runs fine.
It is the combination of GPU and multiprocessing that leads to this error.
```
process Process-2:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 1134, in _apply_pipes
    sender.send([doc.to_bytes() for doc in docs])
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 1134, in <listcomp>
    sender.send([doc.to_bytes() for doc in docs])
  File "nn_parser.pyx", line 253, in pipe
  File "nn_parser.pyx", line 273, in spacy.syntax.nn_parser.Parser.predict
  File "nn_parser.pyx", line 286, in spacy.syntax.nn_parser.Parser.greedy_parse
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 167, in __call__
    return self.predict(x)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 131, in predict
    y, _ = self.begin_update(X, drop=None)
  File "_parser_model.pyx", line 243, in spacy.syntax._parser_model.ParserModel.begin_update
  File "_parser_model.pyx", line 293, in spacy.syntax._parser_model.ParserStepModel.__init__
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/spacy/_ml.py", line 791, in flatten
    lengths = ops.asarray([len(seq) for seq in seqs], dtype="i")
  File "ops.pyx", line 1001, in thinc.neural.ops.CupyOps.asarray
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/cupy/creation/from_data.py", line 43, in array
    return core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/core/core.pyx", line 1954, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2031, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2106, in cupy.core.core._send_object_to_gpu
  File "cupy/core/core.pyx", line 136, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 569, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1241, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1261, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/device.pyx", line 24, in cupy.cuda.device.get_device_id
  File "cupy/cuda/runtime.pyx", line 250, in cupy.cuda.runtime.getDevice
  File "cupy/cuda/runtime.pyx", line 222, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInitializationError: initialization error
Process Process-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 1134, in _apply_pipes
    sender.send([doc.to_bytes() for doc in docs])
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 1134, in <listcomp>
    sender.send([doc.to_bytes() for doc in docs])
  File "nn_parser.pyx", line 253, in pipe
  File "nn_parser.pyx", line 273, in spacy.syntax.nn_parser.Parser.predict
  File "nn_parser.pyx", line 286, in spacy.syntax.nn_parser.Parser.greedy_parse
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 167, in __call__
    return self.predict(x)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 131, in predict
    y, _ = self.begin_update(X, drop=None)
  File "_parser_model.pyx", line 243, in spacy.syntax._parser_model.ParserModel.begin_update
  File "_parser_model.pyx", line 293, in spacy.syntax._parser_model.ParserStepModel.__init__
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/spacy/_ml.py", line 791, in flatten
    lengths = ops.asarray([len(seq) for seq in seqs], dtype="i")
  File "ops.pyx", line 1001, in thinc.neural.ops.CupyOps.asarray
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/cupy/creation/from_data.py", line 43, in array
    return core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/core/core.pyx", line 1954, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2031, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2106, in cupy.core.core._send_object_to_gpu
  File "cupy/core/core.pyx", line 136, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 569, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1241, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1261, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/device.pyx", line 24, in cupy.cuda.device.get_device_id
  File "cupy/cuda/runtime.pyx", line 250, in cupy.cuda.runtime.getDevice
  File "cupy/cuda/runtime.pyx", line 222, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInitializationError: initialization error
```

**Comment by honnibal** [comment]
Thanks for the report. We probably should have foreseen this when we did the multiprocessing for `nlp.pipe`.

I think it's very reasonable to want this, but it's also pretty hard to solve. Processes cannot be forked after CUDA initialization: https://stackoverflow.com/questions/54808148/cupy-get-error-in-multithread-pool-if-gpu-already-used

I think for now we should raise a better error explaining that multiprocessing is not supported with GPU currently, and linking to a workaround if possible. Definitely open to suggestions for how to actually support it.

**Comment by zhanwen** [comment]
@honnibal Thanks，close。

**Comment by floschne** [comment]
I was able to resolve it by adding `multiprocessing.set_start_method('spawn')` in my main method as the first statement.
This causes the process to spawn instead of forking apart from the process that initialized CUDA. The processes then all use CUDA quite efficiently

gpustat output:
`
[7] GeForce RTX 2080 Ti | 38'C, 25 % | 9850 / 11019 MB | 7schneid(1037M) 7schneid(1519M) 7schneid(1541M) 7schneid(1491M) 7schneid(1405M) 7schneid(1355M) 7schneid(1485M)
`

**Comment by ginward** [comment]
I am having similar issues with the following code: 
```

from joblib import Parallel, delayed
from itertools import cycle
import cupy
import spacy
from thinc.api import set_gpu_allocator, require_gpu


def chunker(iterable, total_length, chunksize):
    return (iterable[pos: pos + chunksize] for pos in range(0, total_length, chunksize))

def flatten(list_of_lists):
    "Flatten a list of lists to a combined list"
    return [item for sublist in list_of_lists for item in sublist]

def process_entity(doc):
    super_word_ls = []
    for s in doc.sents:
        word_ls = []
        for t in s:
            if not t.ent_type_:
                if (t.text.strip()!=""):
                    word_ls.append(t.text)
            else:
                word_ls.append(t.ent_type_)
        if len(word_ls)>0:
            super_word_ls.append(" ".join(word_ls))
    return " ".join(super_word_ls)

def process_chunk(texts, rank):
    print(rank)
    with cupy.cuda.Device(rank):
        set_gpu_allocator("pytorch")
        require_gpu(rank)
        nlp = spacy.load("en_core_web_trf")
        preproc_pipe = []
        for doc in nlp.pipe(texts, batch_size=20):
            preproc_pipe.append(process_entity(doc))
        rank+=1
        return preproc_pipe


def preprocess_parallel(texts, chunksize=100):
    executor = Parallel(n_jobs=2, backend='multiprocessing', prefer="processes")
    do = delayed(process_chunk)
    tasks = []
    gpus = list(range(0, cupy.cuda.runtime.getDeviceCount()))
    rank = 0
    for chunk in chunker(texts, len(texts), chunksize=chunksize):
        tasks.append(do(chunk, rank))
        rank = (rank+1)%len(gpus)
    result = executor(tasks)
    return flatten(result)

preprocess_parallel(texts = ["His friend Nicolas J. Smith is here with Bart Simpon and Fred."]*100, chunksize=50)

```

```
RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/software/master/python/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/jw983/rds/hpc-work/pytorch-env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/jw983/rds/hpc-work/pytorch-env/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/jw983/rds/hpc-work/pytorch-env/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "<ipython-input-2-8d88d620b921>", line 31, in process_chunk
    with cupy.cuda.Device(rank):
  File "cupy/cuda/device.pyx", line 160, in cupy.cuda.device.Device.__enter__
  File "cupy_backends/cuda/api/runtime.pyx", line 289, in cupy_backends.cuda.api.runtime.getDevice
  File "cupy_backends/cuda/api/runtime.pyx", line 261, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInitializationError: initialization error
"""

The above exception was the direct cause of the following exception:

CUDARuntimeError                          Traceback (most recent call last)
<ipython-input-2-8d88d620b921> in <module>
     52     return flatten(result)
     53
---> 54 preprocess_parallel(texts = ["His friend Nicolas J. Smith is here with Bart Simpon and Fred."]*100, chunksize=50)
     55
     56

<ipython-input-2-8d88d620b921> in preprocess_parallel(texts, chunksize)
     49         tasks.append(do(chunk, rank))
     50         rank = (rank+1)%len(gpus)
---> 51     result = executor(tasks)
     52     return flatten(result)
     53

~/rds/hpc-work/pytorch-env/lib/python3.7/site-packages/joblib/parallel.py in __call__(self, iterable)
   1052
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

~/rds/hpc-work/pytorch-env/lib/python3.7/site-packages/joblib/parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

/usr/local/software/master/python/3.7/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658
    659     def _set(self, i, obj):

CUDARuntimeError: cudaErrorInitializationError: initialization error
```
