### ISSUE TITLE
GPU is not accessible. Was the library installed correctly?

### ISSUE THREAD

**Issue by gullibleretorted** [explosion/spaCy#6586]
Hi there,

I am using spacy for NER. Unfortunately, I realized that spacy is currently not using my GPU - when I run:
```
import spacy 
spacy.require_gpu() 
```
I get the following error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-a9387f8dcc0a> in <module>
      1 import spacy
      2 
----> 3 spacy.require_gpu()

~/.local/lib/python3.7/site-packages/thinc/util.py in require_gpu(gpu_id)

ValueError: GPU is not accessible. Was the library installed correctly?
```

I have CUDA version 11.0: 

nvcc –version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0

So I installed torch, torchvision and torchaudio accordingly:
pip install torch===1.7.1+cu110 torchvision===0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

Following I installed spacy:
pip install -U spacy-nightly[cuda110,transformers,lookups] --pre

my packages:
```
jupyter:~$ pip list
Package                           Version
--------------------------------- -----------
alembic                           1.4.3
asn1crypto                        0.24.0
async-generator                   1.10
attrs                             20.3.0
backcall                          0.2.0
bleach                            3.2.1
blis                              0.4.1
boto3                             1.16.14
botocore                          1.19.14
catalogue                         1.0.0
certifi                           2020.6.20
certipy                           0.1.3
cffi                              1.12.3
chardet                           3.0.4
click                             7.1.2
conda                             4.8.1
conda-package-handling            1.3.11
cryptography                      2.7
cupy-cuda110                      8.2.0
cycler                            0.10.0
cymem                             2.0.4
Cython                            0.29.21
dataclasses                       0.6
de-core-news-lg                   3.0.0a0
de-core-news-sm                   3.0.0a0
decorator                         4.4.2
defusedxml                        0.6.0
en-core-web-sm                    3.0.0a0
entrypoints                       0.3
et-xmlfile                        1.0.1
fastrlock                         0.5
filelock                          3.0.12
ftfy                              5.8
future                            0.18.2
idna                              2.8
importlib-metadata                2.0.0
ipykernel                         5.3.4
ipython                           7.19.0
ipython-autotime                  0.2.0
ipython-genutils                  0.2.0
ipywidgets                        7.5.1
jdcal                             1.4.1
jedi                              0.17.2
Jinja2                            2.11.2
jmespath                          0.10.0
joblib                            0.17.0
json5                             0.9.5
jsonschema                        3.2.0
jupyter-client                    6.1.7
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.6.3
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.4.1
jupyterhub                        1.0.0
jupyterlab                        2.2.9
jupyterlab-pygments               0.1.2
jupyterlab-server                 1.2.0
kiwisolver                        1.3.1
libarchive-c                      2.8
lxml                              4.6.2
Mako                              1.1.3
MarkupSafe                        1.1.1
matplotlib                        3.3.3
mistune                           0.8.4
murmurhash                        1.0.4
nbclient                          0.5.1
nbconvert                         6.0.7
nbformat                          5.0.8
nbgitpuller                       0.7.2
nbresuse                          0.3.6
nest-asyncio                      1.4.2
networkx                          2.5
notebook                          6.0.3
nteract-on-jupyter                2.1.3
numpy                             1.19.4
oauthlib                          3.1.0
openpyxl                          3.0.5
packaging                         20.4
pamela                            1.0.0
pandas                            1.1.4
pandocfilters                     1.4.3
parso                             0.7.1
pathy                             0.3.1
pexpect                           4.8.0
pickleshare                       0.7.5
Pillow                            8.0.1
pip                               20.3.3
plac                              1.1.3
preshed                           3.0.4
prometheus-client                 0.8.0
prompt-toolkit                    3.0.8
psutil                            5.7.3
ptyprocess                        0.6.0
pycosat                           0.6.3
pycparser                         2.19
pydantic                          1.6.1
Pygments                          2.7.2
pyOpenSSL                         19.0.0
pyparsing                         2.4.7
pyrsistent                        0.17.3
PySocks                           1.7.0
python-dateutil                   2.8.1
python-editor                     1.0.4
pytokenizations                   0.7.2
pytz                              2020.4
PyYAML                            5.3.1
pyzmq                             19.0.2
regex                             2020.10.28
requests                          2.22.0
ruamel-yaml                       0.15.46
s3transfer                        0.3.3
sacremoses                        0.0.43
scikit-learn                      0.23.2
scipy                             1.5.4
Send2Trash                        1.5.0
sentencepiece                     0.1.94
setuptools                        41.0.1
six                               1.12.0
sklearn                           0.0
smart-open                        2.2.1
spacy                             2.2.4
spacy-lookups-data                1.0.0rc0
spacy-nightly                     3.0.0rc2
spacy-transformers                1.0.0rc0
SQLAlchemy                        1.3.20
srsly                             1.0.5
terminado                         0.9.1
testpath                          0.4.4
thinc                             7.4.0
threadpoolctl                     2.1.0
tokenizers                        0.8.1rc1
torch                             1.7.1+cu110
torchaudio                        0.7.2
torchcontrib                      0.0.2
torchvision                       0.8.2+cu110
tornado                           6.0.3
tqdm                              4.51.0
traitlets                         5.0.5
transformers                      3.0.2
typer                             0.3.2
typing-extensions                 3.7.4.3
urllib3                           1.25.11
wasabi                            0.8.0
wcwidth                           0.2.5
webencodings                      0.5.1
wheel                             0.36.2
widgetsnbextension                3.5.1
xlrd                              1.2.0
xx-ent-wiki-sm                    2.2.0
zipp                              3.4.0
```

Thanks a lot in advance for any help!!

## Your Environment
* Operating System: Windows 10
* Python Version Used: python3.7
* spaCy Version Used: 2.2.4
* Environment Information:

**Comment by adrianeboyd** [comment]
What matters for basic spacy usage is whether the `cupy` module is installed correctly. Try this to test `cupy` on its own to see if it works (or if you get a more useful error):

```python
import cupy
a = cupy.zeros((1,1))
```

**Comment by gullibleretorted** [comment]
Thanks, that helped a lot! In the end it was the case that a coworker was using all the RAM of the GPU. It is working now, thanks again for this fast response
