### ISSUE TITLE
CUDA OOM with long documents

### ISSUE THREAD

**Issue by maxmealy** [explosion/spaCy#7268]
I'm running spacy v3.0.3 with python 3.6 on linux with an RTX 2080Ti using the en_core_web_trf model.

With longer documents, I'm getting a CUDA OOM error even processing a single document. Is there any way to control how many batches are sent to the GPU at a time? Or other recommended ways to handle this? 

Here's a reproducible example:

```python
import spacy
spacy.require_gpu() # True
nlp = spacy.load("en_core_web_trf")
text = "Carmen (French: [kaʁ.mɛn]) is an opera in four acts by French composer Georges Bizet. The libretto was written by Henri Meilhac and Ludovic Halévy, based on a novella of the same title by Prosper Mérimée. The opera was first performed by the Opéra-Comique in Paris on 3 March 1875, where its breaking of conventions shocked and scandalized its first audiences."
len(text)  # 360
doc = nlp(text)
long_text = " ".join(text for i in range(1000))
len(long_text)  # 360999
doc = nlp(long_text)

cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 488,455,168 bytes (allocated so far: 1,098,399,744 bytes).
```

**Comment by PhysicsBen** [comment]
I have a similar issue but on the training side. I run out of memory on a Tesla T4 (14 Gb) for even the smallest batch sizes. The max length of my text is < 750 tokens, which I think I am excluding with the config file using corpora.train max_length = 50?

**Comment by kdutia** [comment]
I'm getting the same problem when running `nlp.pipe`. Setting the `batch_size` argument seems to help a bit, but after a while I still get an OutOfMemoryError. 

I'm using an AWS p3.2xlarge (with a Tesla V100).

**Comment by svlandeg** [comment]
Thanks all for the reports. I'm going to merge this with https://github.com/explosion/spaCy/issues/7593 and close this particular issue so we keep the discussion in one place. But this is definitely something that we should dig into further.

**Comment by adrianeboyd** [comment]
Let me reopen this because I think it's a separate issue from the suspected memory leaks in #7593.

**Comment by adrianeboyd** [comment]
So I think you run out of memory for the same reason you can run out of RAM with long documents. The underlying spacy models, especially the `parser` and `ner` models do not scale to indefinitely long documents, also not on CPU.

A very rough rule of thumb for the CNN (non-transformer) pretrained pipelines is that you need 1 GB of RAM for each 100K characters in the text (estimates probably based on an English char-to-token ratio, so this is not particularly generalizable), so the pipelines currently have a default `max_length` of 1M chars. This isn't really a rigit limit, but it lets us show an error in cases where many users might start running into OOM errors, say, on a typical laptop. You can raise it if you need to, for example, if you're only running the tokenizer, or if you have a server with a ton of RAM. For the transformer models, you would also have the transformer model and the additional tensors for the doc stored on the GPU, too, which limits the remaining memory.

This means that the `max_length` limit is too high for the warning to be useful for a lot of GPU use cases, but given all the brittleness around GPU memory management, I think it's going to be up to users to some degree to manage this themselves, by processing shorter documents and/or lowering the batch size.

For the built-in spacy components, there's no real benefit to processing longer texts vs. splitting a text up into meaningful units like chapters, sections, or paragraphs. Most of the linguistic annotation is based on relatively local features, and there shouldn't be entities or dependency arcs that cross section or paragraph boundaries. There can be some minor differences in the entity predictions at the edge of a paragraph without preceding context, but you can process overlapping segments and merge the entity annotation if this turns out to be a noticeable problem for your data. Here's a note about a similar case: https://github.com/explosion/spaCy/issues/4698#issuecomment-557893118

**Comment by adrianeboyd** [comment]
If anyone is still running into issues related to training or OOM not related to large batches/documents, please open a new discussion thread with the details for your training config/setup and the code where you're running into problems!

**Comment by maxmealy** [comment]
Thanks for the explanation @adrianeboyd 

Splitting up texts before it enters the pipeline isn't always a good option. It would add extra complexity for applications that need to operate on whole documents.

I guess this is more of a feature request, but, it would be really great to see spacy just handle the batching and memory management under the hood. I assume there is already batching going on with the transformers, so, maybe this is just a question of moving those vectors off the GPU?

**Comment by polm** [comment]
> I guess this is more of a feature request, but, it would be really great to see spacy just handle the batching and memory management under the hood. I assume there is already batching going on with the transformers, so, maybe this is just a question of moving those vectors off the GPU?

This would be a great feature to have, but the right way to split up long documents is going to vary by application, so it's hard for us to make something useful without a particular application in mind. Like Adriane said this is going to have to be left up to the user to some degree.

**Comment by maxmealy** [comment]
I see your point @polm. There probably are a lot of custom ways to split up documents using patterns, etc that require domain knowledge. While probably not hard to implement with the Sentencizer/Matcher, that's not what I had in mind with this. The huggingface tokenizer already has ways to control long documents and users can configure the truncation/stride/padding/overflow behavior in the tokenizer_config.

It sounds like the issue is happening after the transformer has run. Outputs are being left on the GPU and the ner/parser models are trying to operate on hundreds of thousands of tokens and getting an OOM. What if each model was responsible for moving things on/off the GPU before/after inference, and the models operated on batches within the documents?
