### ISSUE TITLE
System reboot automatically on using gpu with spacy train cli

### ISSUE THREAD

**Issue by shv07** [explosion/spaCy#7747]
## How to reproduce the behaviour

I was trying to train a NER model (with transformers) using the official recommended config system. The process runs fine when I am not using the gpu (i.e. not using any flag ```-g 0```. But when I use that flag, after the first step of training, there is a crash and the system restarts itself.  The spacy's training command line output does not print any error though.

But I am able to infer with en_core_web_trf on gpu, and also run spacy v2 ner training on gpu (without transformers)

## Info about spaCy

- **spaCy version:** 3.0.5
- **Platform:** Linux-4.4.0-206-generic-x86_64-with-Ubuntu-16.04-xenial
- **Python version:** 3.6.13
- **Pipelines:** en_core_web_trf (3.0.0)
- **Cuda:**  10.1
- **Gpu:** Nvidia Quadro RTX 6000

**Comment by svlandeg** [comment]
What exactly do you mean by "restarts itself"?

There's not a lot of information to go by, so this is a shot in the dark, but have you tried monitoring your memory usage to see whether perhaps that's the problem?

**Comment by shv07** [comment]
> What exactly do you mean by "restarts itself"?
> 
> There's not a lot of information to go by, so this is a shot in the dark, but have you tried monitoring your memory usage to see whether perhaps that's the problem?

Thanks for the prompt reply. By "restarts itself", I meant the machine on which I am running the training config, reboots itself (without throwing any kind of error message). 

I tried monitoring memory usage too on your suggestion. It was around 50% when it started to reboot. Tried checking the GPU usage with nvidia-smi. The gpu usage kept increasing from around 100 MB and just before reboot, the usage was around 2000 MB.

**Comment by svlandeg** [comment]
> By "restarts itself", I meant the machine on which I am running the training config, reboots itself and without throwing any kind of error message. 

Oh, wow, that is quite drastic :| Sorry to hear you've been running into this!

As you can infer predictions with GPU, this doesn't seem to be an install problem. On the other hand, when I run things on my small little GPU on my laptop, it will properly terminate with an error (e.g. out of memory or what not) rather than crashing the entire system. So I'm not sure how to progress with debugging this, even though the behaviour you're seeing is definitely a problem.

I think if I were you, the other thing I'd try is to just make an extremely small version of your training dataset (like 1 or 2 examples), and try training on that, just to verify that the training loop actually runs fine on GPU. If that works, we must find the culprit in the system resources somehow, right? 

I'll continue thinking about this though, if I can come up with other ideas I'll let you know. Or if anyone else has a clue - feel free to chime in!

**Comment by polm** [comment]
I have never had an issue like this, but looking around it does seem like something people run into with GPU training sometimes. It seems it may be due to hardware compatibility or power supply issues.

In [this post](https://discuss.pytorch.org/t/system-reboot-when-training/108317/2) a similar issue was fixed by limiting GPU power usage, which you can do with nvidia-smi apparently. Some people in this [older issue](https://github.com/pytorch/pytorch/issues/3022) also used a similar fix.

**Comment by shv07** [comment]
> I have never had an issue like this, but looking around it does seem like something people run into with GPU training sometimes. It seems it may be due to hardware compatibility or power supply issues.
> 
> In [this post](https://discuss.pytorch.org/t/system-reboot-when-training/108317/2) a similar issue was fixed by limiting GPU power usage, which you can do with nvidia-smi apparently. Some people in this [older issue](https://github.com/pytorch/pytorch/issues/3022) also used a similar fix.

Thanks. The approach of limiting the GPU power usage didn't work for me yet. I will go over these posts and try to get a workaround if possible..

**Comment by shv07** [comment]
I was finally able to train without any issues after getting the PSU replaced with one with higher power supply (earlier it was 600 W PSU, later replaced with 1200 W PSU).

Following things did not work out :-
- Trying to limit GPU power usage with nvidia-smi
- Turning off turbo boost of cpu
- re-installing drivers and cuda libraries

Thanks!

**Comment by svlandeg** [comment]
Thanks so much for reporting back! That's always useful for future reference, and I'm happy to hear you were able to get this fixed!

**Comment by shv07** [comment]
You're welcome! :)

**Comment by escyes** [comment]
It worked for me to deactivate the intel turbo boost which seems to indicate that it is a cpu problem, when I monitor the temperature of the cpu cores before deactivating boost it rose very quickly to 60 degrees now it stays at less than 50
it happens to me with a NMIST example and in batch 7 pytorch only
