### ISSUE TITLE
Cuda OOM using train cli on AWS Sagemaker ml.p3.2xlarge

### ISSUE THREAD

**Issue by drisspg** [explosion/spaCy#8191]
## How to reproduce the behaviour

My config file is as below:
```
[paths]
train = null
dev = null
vectors = null
init_tok2vec = null

[system]
gpu_allocator = "pytorch"
seed = 0

[nlp]
lang = "en"
pipeline = ["transformer","ner","textcat_multilabel"]
batch_size = 64
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.ner]
factory = "ner"
moves = null
update_with_oracle_cut_size = 100

[components.ner.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "ner"
extra_state_tokens = false
hidden_width = 64
maxout_pieces = 2
use_upper = false
nO = null

[components.transformer]
factory = "transformer"
max_batch_items = 4096
set_extra_annotations = {"@annotation_setters":"spacy-transformers.null_annotation_setter.v1"}

[components.transformer.model]
@architectures = "spacy-transformers.TransformerModel.v1"
name = "roberta-base"

[components.transformer.model.get_spans]
@span_getters = "spacy-transformers.strided_spans.v1"
window = 128
stride = 96

[components.transformer.model.tokenizer_config]
use_fast = true

[components.ner.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "*"

[components.textcat_multilabel]
factory = "textcat_multilabel"
threshold = 0.5

[components.textcat_multilabel.model]
@architectures = "spacy.TextCatEnsemble.v2"
nO = null

[components.textcat_multilabel.model.linear_model]
@architectures = "spacy.TextCatBOW.v1"
exclusive_classes = false
ngram_size = 3
no_output_layer = false
nO = null

[components.textcat_multilabel.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "*"


[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 500
gold_preproc = false
limit = 0
augmenter = null

[training]
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
accumulate_gradient = 1
patience = 2000
max_epochs = 0
max_steps = 200000
eval_frequency = 200
frozen_components = []
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_padded.v1"
discard_oversize = true
size = 500
buffer = 128
get_length = null


[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = true

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001

[training.optimizer.learn_rate]
@schedules = "warmup_linear.v1"
warmup_steps = 250
total_steps = 20000
initial_rate = 0.00005


[training.score_weights]
ents_per_type = null
cats_score_desc = null
cats_micro_p = null
cats_micro_r = null
cats_micro_f = null
cats_macro_p = null
cats_macro_r = null
cats_macro_f = null
cats_macro_auc = null
cats_f_per_type = null
cats_macro_auc_per_type = null
ents_f = 0.5
ents_p = 0.0
ents_r = 0.0
cats_score = 0.5

[pretraining]

[initialize]
vectors = null
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
before_init = null
after_init = null

[initialize.components]

[initialize.components.ner]

[initialize.components.ner.labels]
@readers = "spacy.read_labels.v1"
path = "<Path>"
require = false

[initialize.components.textcat_multilabel]

[initialize.components.textcat_multilabel.labels]
@readers = "spacy.read_labels.v1"
path = "<path>"
require = false

[initialize.tokenizer]

[initialize.lookups]
@misc = "spacy.LookupsDataLoader.v1"
lang = ${nlp.lang}
tables = ["lexeme_norm"]
```

## Your Environment

* Operating System: Running on sage maker ml.p3.2xlarge, Tesla V100-SXM2 16 gb.
* Python Version Used: 3.7.10
* spaCy Version Used: 3.0.6
* Environment Information: spacy[cuda102]

I am running training with `python -m spacy train` and am continually running into a CUDA OOM error.  I have trained adjusting the batch size, corpora max_length and the training.batcher size.  The first two had no effect whatsoever. Only changing the training batcher size had an effect. I lowered both the size from 2000 to 500 and buffer from 256 to 128. This delayed the OOM error however this only prolonged the inevitable as nvidia-smi shows the memory usage slowly creeping up till eventually the below error is encountered..  My corpra is 70k docs all with a max char length of 800 and 5k docs in the dev/gold set which makes me believe it is not a problem with long document sizes as I have seen in other CUDA OOM discussions.  I have also read https://spacy.io/api/top-level#batch_by_padded to try and get a better grasp on how exactly the batching is done.  I'm not sure how nlp.batch_size effects the batch_size during training but I assume that training.batcher completely override the setting defined under nlp.

I have adapted a previous config that was based on the en_core_web_md and a tok2vec component instead of a transformer, maybe there is some hidden config parameter that is incorrectly set but I also used the config Quickstart and don't see anything jumping out. 

Exact error
```
 File "/home/ec2-user/SageMaker/upchuck-venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/SageMaker/upchuck-venv/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ec2-user/SageMaker/upchuck-venv/lib/python3.7/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 15.78 GiB total capacity; 14.23 GiB already allocated; 34.75 MiB free; 14.35 GiB reserved in total by PyTorch)
```

**Comment by brightgems** [comment]
I happen to see OOM error with bert also resently, after cut training corpuse to 128 chars each document, this issue disappeared. I though you might need proper preprocess on training corpus.
